language: node_js
node_js:
  - 8
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache
script:
  - yarn clean
  - yarn test
deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    node_js: 8
    on:
      master: true
