language: node_js
node_js: 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - $HOME/.cache
    - public

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: test
      node_js: 10
      script: yarn test
    - stage: lighthouse
      if: type = pull_request
      install: yarn add --dev wait-for-now
      script: yarn lh "$(wait-for-now)"

deploy:
  provider: script
  script: bash create-alias.sh
  skip_cleanup: true
  node_js: 8
  on:
    master: true
