language: node_js
node_js:
  - 8
  - 10
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm link bs-platform
  - yarn clean
  - yarn test
