dist: xenial
language: node_js
node_js: 8

# https://github.com/GoogleChrome/lighthouse/issues/7076#issuecomment-458611891
addons:
  chrome: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - $HOME/.cache
    - public

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: test
      node_js: 10
      script: yarn test
    - stage: code coverage
      if: type = push
      install: yarn add --dev coveralls
      script: yarn test --maxWorkers=2 --coverage --coverageReporters=text-lcov | coveralls
    - stage: lighthouse
      if: type = pull_request
      install: yarn add --dev https://github.com/GoogleChromeLabs/lighthousebot wait-for-now
      script: lighthousebot "$(wait-for-now)"

deploy:
  provider: script
  script: bash create-alias.sh
  skip_cleanup: true
  node_js: 8
  on:
    master: true
